version: '2'
services:
  kira:
    image: kira
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://kira-postgresql:5432/kira'
      - JHIPSTER_SLEEP=30
    ports:
      - '8080:8080'
  kira-postgresql:
    image: 'postgres:12.3'
    environment:
      - POSTGRES_USER=kira
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
